# Generated by Django 3.0.5 on 2020-04-27 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(related_name='_userprofile_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
