# Generated by Django 3.0.5 on 2020-04-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200427_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follows',
        ),
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
