# Generated by Django 3.0.5 on 2020-05-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hotsearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchkey',
            old_name='value',
            new_name='key_content',
        ),
        migrations.AlterField(
            model_name='searchkey',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='searchkey',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
