# Generated by Django 3.0.5 on 2020-05-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0004_auto_20200511_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=7),
        ),
    ]
